marks=[]
f1=int(input("Enter marks Number=>"))
marks.append(f1)
f2=int(input("Enter marks Number=>"))
marks.append(f2)
f3=int(input("Enter marks Number=>"))
marks.append(f3)
f4=int(input("Enter marks Number=>"))
marks.append(f4)
f5=int(input("Enter marks Number=>"))
marks.append(f5)
f6=int(input("Enter marks Number=>"))
marks.append(f6)
f7=int(input("Enter marks Number=>"))
marks.append(f7)
f8=int(input("Enter marks Number=>"))
marks.append(f8)

marks.sort()
print(marks)