frout=[]
f1=input("Enter Frout Name=>")
frout.append(f1)
f2=input("Enter Frout Name=>")
frout.append(f2)
f3=input("Enter Frout Name=>")
frout.append(f3)
f4=input("Enter Frout Name=>")
frout.append(f4)
f5=input("Enter Frout Name=>")
frout.append(f5)
f6=input("Enter Frout Name=>")
frout.append(f6)
f7=input("Enter Frout Name=>")
frout.append(f7)
f8=input("Enter Frout Name=>")
frout.append(f8)

print(frout)